// Is there a better way to check versions? Haven't really looked into it.
if (parseInt(process.versions.node.split('.')[0]) >= 8) {
  // Native (Node 8+) ES6. (Requires async / await.)
  module.exports = require('./es6/prerender.js')
} else {
  // Transpiled through babel to target Node 4+.
  module.exports = require('./es5-autogenerated/prerender.js')
}
